---

- name: install buster-backports repo
  apt_repository:
    repo: deb http://deb.debian.org/debian buster-backports main
    state: present
    update_cache: yes
  when: ansible_distribution_release == "buster"

- name: install required packages
  apt:
    pkg:
      - wireguard
      - qrencode
      - netfilter-persistent # Debian >10 uses netfilter with the iptables-nf translation layer
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: ensure wireguard conf dir
  tags: [ show_wg_client_conf ]
  file:
    path: "{{ wg_conf_path }}"
    state: directory
  register: wg_conf_dir

- name: Update SystemCtl Settings
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes
  when: ansible_os_family == "Debian"

- name: ensure wireguard port open on iptables
  ansible.builtin.iptables:
    action: append
    chain: INPUT
    destination_port: "{{ wg_port }}"
    protocol: udp
    jump: ACCEPT
  when: ansible_os_family == "Debian"

- name: create server keys
  ansible.builtin.shell:
    chdir: "{{ wg_conf_dir.path }}"
    cmd: |
      if [ ! -f server_privkey ] || [ ! -f server_pubkey ]; then
        umask 077 && wg genkey | tee server_privkey | wg pubkey > server_pubkey
        echo "GENERATED NEW SERVER KEYS"
      fi
  # TODO: Capture if these have been regenerated and ensure that gets alerted. (Clients won't work anymore!)

- name: get server pubkey
  ansible.builtin.slurp:
    src: "{{ wg_conf_dir.path }}/server_pubkey"
  register: server_pubkey

- name: get server privkey
  ansible.builtin.slurp:
    src: "{{ wg_conf_dir.path }}/server_privkey"
  register: server_privkey

- name: get server public IPv4 address
  uri: 
    url: "https://ipv4.icanhazip.com"
    remote_src: yes
    return_content: yes
  register: server_public_ipv4
